[env:m5stack-dial]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_flags =
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  m5stack/M5Dial@^1.0.2
  sparkfun/SparkFun Qwiic Keypad Arduino Library@^1.2.0
